// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/configguard/v1/configguard.proto

package configguardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_FORMAT_UNSPECIFIED Format = 0
	Format_FORMAT_JSON        Format = 1
	Format_FORMAT_YAML        Format = 2
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_JSON",
		2: "FORMAT_YAML",
	}
	Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_JSON":        1,
		"FORMAT_YAML":        2,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_configguard_v1_configguard_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_api_proto_configguard_v1_configguard_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_configguard_v1_configguard_proto_rawDescGZIP(), []int{0}
}

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_LOW         Level = 1
	Level_LEVEL_MEDIUM      Level = 2
	Level_LEVEL_HIGH        Level = 3
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_LOW",
		2: "LEVEL_MEDIUM",
		3: "LEVEL_HIGH",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_LOW":         1,
		"LEVEL_MEDIUM":      2,
		"LEVEL_HIGH":        3,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_configguard_v1_configguard_proto_enumTypes[1].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_api_proto_configguard_v1_configguard_proto_enumTypes[1]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_configguard_v1_configguard_proto_rawDescGZIP(), []int{1}
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Format        Format                 `protobuf:"varint,2,opt,name=format,proto3,enum=configguard.v1.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_configguard_v1_configguard_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ScanRequest) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

type Issue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleId         string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Level          Level                  `protobuf:"varint,2,opt,name=level,proto3,enum=configguard.v1.Level" json:"level,omitempty"`
	Field          string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_api_proto_configguard_v1_configguard_proto_rawDescGZIP(), []int{1}
}

func (x *Issue) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Issue) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Issue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	HasIssues     bool                   `protobuf:"varint,2,opt,name=has_issues,json=hasIssues,proto3" json:"has_issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configguard_v1_configguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_configguard_v1_configguard_proto_rawDescGZIP(), []int{2}
}

func (x *ScanResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ScanResponse) GetHasIssues() bool {
	if x != nil {
		return x.HasIssues
	}
	return false
}

var File_api_proto_configguard_v1_configguard_proto protoreflect.FileDescriptor

const file_api_proto_configguard_v1_configguard_proto_rawDesc = "" +
	"\n" +
	"*api/proto/configguard/v1/configguard.proto\x12\x0econfigguard.v1\"U\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12.\n" +
	"\x06format\x18\x02 \x01(\x0e2\x16.configguard.v1.FormatR\x06format\"\xa5\x01\n" +
	"\x05Issue\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12+\n" +
	"\x05level\x18\x02 \x01(\x0e2\x15.configguard.v1.LevelR\x05level\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\"\\\n" +
	"\fScanResponse\x12-\n" +
	"\x06issues\x18\x01 \x03(\v2\x15.configguard.v1.IssueR\x06issues\x12\x1d\n" +
	"\n" +
	"has_issues\x18\x02 \x01(\bR\thasIssues*B\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vFORMAT_JSON\x10\x01\x12\x0f\n" +
	"\vFORMAT_YAML\x10\x02*O\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tLEVEL_LOW\x10\x01\x12\x10\n" +
	"\fLEVEL_MEDIUM\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_HIGH\x10\x032S\n" +
	"\x0eScannerService\x12A\n" +
	"\x04Scan\x12\x1b.configguard.v1.ScanRequest\x1a\x1c.configguard.v1.ScanResponseB<Z:configguard/internal/genproto/configguard/v1;configguardv1b\x06proto3"

var (
	file_api_proto_configguard_v1_configguard_proto_rawDescOnce sync.Once
	file_api_proto_configguard_v1_configguard_proto_rawDescData []byte
)

func file_api_proto_configguard_v1_configguard_proto_rawDescGZIP() []byte {
	file_api_proto_configguard_v1_configguard_proto_rawDescOnce.Do(func() {
		file_api_proto_configguard_v1_configguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_configguard_v1_configguard_proto_rawDesc), len(file_api_proto_configguard_v1_configguard_proto_rawDesc)))
	})
	return file_api_proto_configguard_v1_configguard_proto_rawDescData
}

var file_api_proto_configguard_v1_configguard_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_configguard_v1_configguard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_configguard_v1_configguard_proto_goTypes = []any{
	(Format)(0),          // 0: configguard.v1.Format
	(Level)(0),           // 1: configguard.v1.Level
	(*ScanRequest)(nil),  // 2: configguard.v1.ScanRequest
	(*Issue)(nil),        // 3: configguard.v1.Issue
	(*ScanResponse)(nil), // 4: configguard.v1.ScanResponse
}
var file_api_proto_configguard_v1_configguard_proto_depIdxs = []int32{
	0, // 0: configguard.v1.ScanRequest.format:type_name -> configguard.v1.Format
	1, // 1: configguard.v1.Issue.level:type_name -> configguard.v1.Level
	3, // 2: configguard.v1.ScanResponse.issues:type_name -> configguard.v1.Issue
	2, // 3: configguard.v1.ScannerService.Scan:input_type -> configguard.v1.ScanRequest
	4, // 4: configguard.v1.ScannerService.Scan:output_type -> configguard.v1.ScanResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_configguard_v1_configguard_proto_init() }
func file_api_proto_configguard_v1_configguard_proto_init() {
	if File_api_proto_configguard_v1_configguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_configguard_v1_configguard_proto_rawDesc), len(file_api_proto_configguard_v1_configguard_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_configguard_v1_configguard_proto_goTypes,
		DependencyIndexes: file_api_proto_configguard_v1_configguard_proto_depIdxs,
		EnumInfos:         file_api_proto_configguard_v1_configguard_proto_enumTypes,
		MessageInfos:      file_api_proto_configguard_v1_configguard_proto_msgTypes,
	}.Build()
	File_api_proto_configguard_v1_configguard_proto = out.File
	file_api_proto_configguard_v1_configguard_proto_goTypes = nil
	file_api_proto_configguard_v1_configguard_proto_depIdxs = nil
}
